# Setup
title:               Chris Malec
tagline:             'Data Scientist'
description:         'My personal blog about data science, programming, and answering silly questions with powerful tools.'
url:                 http://chris-malec.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
gems:
plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Theme
theme:       jekyll-theme-lanyon

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
